# Generated by Django 3.2.18 on 2024-11-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QAData',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('remark', models.CharField(max_length=150, verbose_name='备注说明')),
            ],
            options={
                'verbose_name': '问答数据',
                'verbose_name_plural': '问答数据',
                'ordering': ['-qid'],
            },
        ),
    ]
